### ISSUE TITLE
datasetName and datasetID

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/inva-occurrences#1]
For `datasetName`, we usually provide the name of the published dataset on GBIF, in this case this would be _Exotic plant occurrences in Wallonia_. However, I understand why you choose to put the information about the original five datasets under `datasetName`. Besides from the field `source`, I see no other option then to put this information under `datasetName`. `source`, however, is a deprecated term in the occurrence core. So there are two options here:

1. Use the TrIAS approach and use _Exotic plant occurrences in Wallonia_ as the datasetName. The references to the original dataset could be put in the metadata.

2. Keep the five original datasets under `datasetName`

I would go for option one, especially to keep it in line with the other TrIAS datasets, but this depends on how visible you want the original datasetnames to be in the download.

In line with this, `datasetID` should in case 1 refer to the doi of the dataset as it is published on GBIF (in this case https://doi.org/10.15468/cqfrx0), and not to a single number.

**Comment by mcoupremanne** [comment]
I 100% agree with following Trias publication line.
May I suggest a last option :
   **3.** - Use  datasetName to refer to the GBIF dataset as it is done with TrIAS. Indeed, adapt DatasetID to mention the DOI of the GBIF dataset rather then the ID of the dataset attributed in the DEMNA's fusion tool (single numbers are our sources IDs).
 **and** - Use collectionCode & CollectionID to keep the information about the source database.

I do not feel that confortable because I was taught 'Collection' only refer to a physical collection. But the [TDWG definition](http://rs.tdwg.org/dwc/terms/#collectionCode) includes datasets (here we would consider our source databases as virtual collections). In the given exemples, 'eBird' is given as collectionCode.


So, according to your opinion, we can go for the options 1. or 3.

**Comment by peterdesmet** [comment]
Yep, `collectionCode` would be a good one for this indeed. I would not use `collectionID`.

**Comment by LienReyserhove** [comment]
Option 3 is absolutely fine (taking in mind Peter's remark)!

**Comment by peterdesmet** [comment]
Just reviewed in v1.5:

- `datasetID` is now the DOI
- `datasetName` is now the title
- `collectionCode` is now the subdataset

👍
